#!/bin/sh
STANFORD_NER_PATH=$STANFORD_NER_ROOT/stanford-ner.jar
STANFORD_NER_MODEL=$STANFORD_NER_ROOT/classifiers/english.all.3class.distsim.crf.ser.gz

MEMORY=700m
ENCODING='utf-8'
PORT=1447
OUTPUT_FORMAT=slashTags
PRESERVE_SPACING="true"

java -Xmx$MEMORY -cp $STANFORD_NER_PATH edu.stanford.nlp.ie.NERServer \
	-loadClassifier $STANFORD_NER_MODEL -port $PORT -encoding $ENCODING \
    -tokenizerFactory edu.stanford.nlp.process.WhitespaceTokenizer \
    -tokenizerOptions "tokenizeNLs=true" \
	-outputFormat $OUTPUT_FORMAT \
    -preserveSpaces $PRESERVE_SPACING
